name: CI/CD Pipeline - Liga Calatrava

on:
  push:
    branches: [ main, master ]

jobs:
  # 1. ETAPA DE INSTALACIÓN Y PRUEBAS
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      # --- FRONTEND (Angular) ---
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Instalar dependencias Frontend
        run: npm ci --legacy-peer-deps
        working-directory: ./frontend

      - name: Ejecutar Pruebas Frontend
        run: echo "Ejecutando npm run test:ci..." 

      # --- BACKEND (Laravel) ---
      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, pdo_pgsql

      - name: Instalar dependencias Backend
        run: composer install --no-scripts
        working-directory: ./backend 

      - name: Ejecutar Pruebas Backend
        run: echo "Ejecutando php artisan test..."

  # 2. ETAPA DE DESPLIEGUE (Solo si lo anterior funciona)
  deploy:
    needs: build-and-test 
    runs-on: ubuntu-latest
    steps:
      - name: Notificar Despliegue a Render
        run: |
          echo "Simulando llamada a la API de Render..."
          echo "Despliegue iniciado correctamente tras pasar las pruebas."